load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "main",
    srcs = ["dev/alanryan/main/Main.java"],
    main_class = "dev.alanryan.main.Main",
    deps = ["//src/utils:greeting"],
)
